name: seyamy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.5.4

# Flutter SDK and essential dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI and styling dependencies
  flutter_svg: ^2.0.14
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4
  smooth_page_indicator: ^1.2.0+3
  device_preview: ^1.2.0
  confetti: ^0.8.0
  flutter_spinkit: ^5.2.1

  # Localization and internationalization
  easy_localization: ^3.0.7

  # NOTIFICATION
  awesome_notifications: ^0.10.0 # android

  # Configuration and utilities
  flutter_native_splash: ^2.4.2
  vibration: ^2.0.1
  rive: ^0.13.15
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.1
  store_redirect: ^2.0.3
  share_plus: ^10.1.2
  jhijri: ^1.0.0

  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_offline: ^4.0.0
  url_launcher: ^6.3.1


  # State management and dependency injection
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  get_it: ^8.0.2
  equatable: ^2.0.5

  # Routing and navigation
  go_router: ^14.4.1


# Dev dependencies
dev_dependencies:
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter


flutter_native_splash:
  background_image: "assets/images/splash_light.png"
  background_image_dark: "assets/images/splash_dark.png"


flutter:
  uses-material-design: true

  # Assets used in the project
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/lang/
    - assets/

  # Fonts used in the project
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-VariableFont.ttf
          weight: 100


flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: